name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          # Create the SSH directory
          mkdir -p ~/.ssh
          # Save the SSH key in the correct location
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          # Secure permissions for the SSH key
          chmod 600 ~/.ssh/id_rsa
          # Add your server to known_hosts to prevent verification issues
          ssh-keyscan -H 64.227.103.202 >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Deploy to Server
        run: |
          ssh -vvv -i ~/.ssh/id_rsa anton@64.227.103.202 'cd /var/www/idleworkshop.com/html && git pull origin main && sudo chown -R www-data:www-data /var/www/idleworkshop.com/html'
